### ISSUE TITLE
LangGraph CLI統合: 開発ワークフローの最適化とデプロイメント自動化

### ISSUE THREAD

**Issue by bebebebebebebebebebebebebebebe** [bebebebebebebebebebebebebebebe/task_management_agents#27]
## 概要
LangGraph CLIを統合して開発ワークフローの最適化とデプロイメント自動化を実現する。

## 背景
現在の開発プロセスでは手動でのテスト実行やデプロイメントが必要。LangGraph CLIを活用することで、開発者の生産性向上とデプロイメントプロセスの標準化が可能。

### 1. プロジェクト構成の最適化
```bash
# プロジェクト初期化（既存コードとの統合）
langgraph new --from-template=multi-agent ./langgraph-config

# 既存エージェントの設定マイグレーション
langgraph config add-graph biz-requirement \
  --path=src.agents.biz_requirement:BizRequirementAgent.build_graph
```

### 2. 設定ファイルの作成
- [ ] `.langgraph/config.yaml` - エージェント設定
- [ ] `.langgraph/requirements.txt` - 依存関係管理
- [ ] `deployment/docker-compose.yml` - コンテナ化設定

### 3. CLI統合スクリプト
```yaml
# .langgraph/config.yaml
graphs:
  biz_requirement:
    path: src.agents.biz_requirement:create_agent_graph
    description: "ビジネス要件定義エージェント"
  requirement_process:
    path: src.agents.requirement_process:create_orchestrator_graph
    description: "技術要件プロセスエージェント"
  integrated_workflow:
    path: src.agents.integrated_workflow:create_workflow_graph
    description: "統合ワークフローエージェント"

deployment:
  production:
    env_file: .env.production
    wait_online: 300
  development:
    debugger_port: 8001
    hot_reload: true
```

### 4. pyproject.tomlへのスクリプト追加
```toml
[project.scripts]
langgraph-dev = "langgraph.cli:dev"
langgraph-deploy = "langgraph.cli:deploy"
langgraph-test = "langgraph.cli:test"
```

## 受け入れ基準
- [ ] `.langgraph/`ディレクトリが正しく設定されている
- [ ] `langgraph dev --debugger-port=8001`で開発モードが起動する
- [ ] `langgraph deploy --alias=production`でデプロイメントができる
- [ ] `langgraph test`で全エージェントのテストが実行される
- [ ] 既存のコマンド(`biz-requirement-agent`等)が引き続き動作する

## 技術的詳細
- **CLI version**: langgraph-cli==0.2.10 (既にインストール済み)
- **設定場所**: `.langgraph/`ディレクトリ
- **デバッグポート**: 8001
- **デプロイメント**: Docker Compose対応

## 関連Issue
- 依存: LangGraph Server統合 (#26)
- 関連: エントリーポイント実装 (#予定)

## 優先度
High - 開発効率とデプロイメント自動化に直結

## 推定工数
2-3日

## 実装手順
1. 既存プロジェクト構造の分析
2. `.langgraph/`設定ファイル群の作成
3. Docker設定の追加
4. CLI統合テストの実行
5. 既存ワークフローとの整合性確認
