### ISSUE TITLE
LangGraph統合用設定ファイル作成: 統合プラットフォーム用の設定管理

### ISSUE THREAD

**Issue by bebebebebebebebebebebebebebebe** [bebebebebebebebebebebebebebebe/task_management_agents#31]
## 概要
LangGraphプラットフォーム統合に必要な各種設定ファイルを作成し、統一的な設定管理を実現する。

## 背景
LangGraph Server、CLI、Studio、SDKの統合には、それぞれ専用の設定ファイルが必要。また、開発・本番環境での設定切り替えや、Docker化対応も含めた包括的な設定管理が求められる。

### 1. LangGraph Server設定
```json
# langgraph.json
{
  \"dependencies\": [\"./\"],
  \"graphs\": {
    \"biz_requirement_agent\": {
      \"path\": \"src.agents.biz_requirement:create_agent_graph\",
      \"config_schema\": {
        \"type\": \"object\",
        \"properties\": {
          \"interactive_mode\": {
            \"type\": \"boolean\",
            \"default\": true,
            \"description\": \"インタラクティブモードの有効化\"
          },
          \"auto_save\": {
            \"type\": \"boolean\",
            \"default\": true,
            \"description\": \"自動保存機能の有効化\"
          },
          \"output_dir\": {
            \"type\": \"string\",
            \"default\": \"outputs\",
            \"description\": \"出力ディレクトリのパス\"
          }
        }
      }
    },
    \"requirement_process_agent\": {
      \"path\": \"src.agents.requirement_process:create_orchestrator_graph\",
      \"config_schema\": {
        \"type\": \"object\",
        \"properties\": {
          \"interactive_mode\": {
            \"type\": \"boolean\",
            \"default\": true,
            \"description\": \"インタラクティブモードの有効化\"
          },
          \"auto_approve\": {
            \"type\": \"boolean\",
            \"default\": false,
            \"description\": \"自動承認モードの有効化\"
          },
          \"max_retry_attempts\": {
            \"type\": \"integer\",
            \"default\": 3,
            \"minimum\": 1,
            \"description\": \"最大リトライ回数\"
          }
        }
      }
    },
    \"integrated_workflow_agent\": {
      \"path\": \"src.agents.integrated_workflow:create_workflow_graph\",
      \"config_schema\": {
        \"type\": \"object\",
        \"properties\": {
          \"enable_persistence\": {
            \"type\": \"boolean\",
            \"default\": true,
            \"description\": \"永続化機能の有効化\"
          },
          \"enable_auto_save\": {
            \"type\": \"boolean\",
            \"default\": true,
            \"description\": \"自動保存機能の有効化\"
          },
          \"intermediate_save\": {
            \"type\": \"boolean\",
            \"default\": true,
            \"description\": \"中間保存機能の有効化\"
          }
        }
      }
    }
  },
  \"env\": \".env\",
  \"server\": {
    \"port\": 8000,
    \"host\": \"0.0.0.0\",
    \"cors\": {
      \"allow_origins\": [\"*\"],
      \"allow_methods\": [\"GET\", \"POST\", \"PUT\", \"DELETE\"],
      \"allow_headers\": [\"*\"]
    }
  }
}
```

### 2. LangGraph CLI設定
```yaml
# .langgraph/config.yaml
project:
  name: \"task_management_agents\"
  version: \"1.0.0\"
  description: \"タスク管理エージェントシステム\"

graphs:
  biz_requirement:
    path: \"src.agents.biz_requirement:create_agent_graph\"
    description: \"ビジネス要件定義エージェント\"
    tags: [\"business\", \"requirements\"]
  
  requirement_process:
    path: \"src.agents.requirement_process:create_orchestrator_graph\"
    description: \"技術要件プロセスエージェント\"
    tags: [\"technical\", \"requirements\", \"orchestrator\"]
  
  integrated_workflow:
    path: \"src.agents.integrated_workflow:create_workflow_graph\"
    description: \"統合ワークフローエージェント\"
    tags: [\"workflow\", \"integration\"]

deployment:
  production:
    env_file: \".env.production\"
    wait_online: 300
    replicas: 2
    resources:
      memory: \"1Gi\"
      cpu: \"500m\"
  
  development:
    env_file: \".env.development\"
    debugger_port: 8001
    hot_reload: true
    log_level: \"DEBUG\"

dependencies:
  python: \">=3.13\"
  requirements_file: \"requirements.txt\"

testing:
  framework: \"pytest\"
  coverage_threshold: 80
  test_paths: [\"tests/\"]
```

```txt
# .langgraph/requirements.txt
langgraph>=0.4.7
langgraph-cli>=0.2.10
langgraph-sdk>=0.1.70
pydantic>=2.0.0
pydantic-settings>=2.9.1
```

### 3. LangGraph Studio設定
```json
# studio-config.json
{
  \"server_url\": \"http://localhost:8000\",
  \"auth_mode\": \"development\",
  \"workspace\": \"task_management_agents\",
  \"auto_sync\": true,
  \"features\": {
    \"visual_debugging\": true,
    \"real_time_monitoring\": true,
    \"collaborative_editing\": false,
    \"version_control\": true
  },
  \"layouts\": {
    \"default\": \"hierarchical\",
    \"alternative\": \"force_directed\",
    \"compact\": \"circular\"
  },
  \"themes\": {
    \"default\": \"dark\",
    \"alternative\": \"light\"
  },
  \"visualization\": {
    \"node_spacing\": 100,
    \"edge_curve\": \"smooth\",
    \"animation_duration\": 300,
    \"show_labels\": true,
    \"show_types\": true
  },
  \"debugging\": {
    \"breakpoints_enabled\": true,
    \"state_inspection\": true,
    \"step_by_step\": true,
    \"performance_monitoring\": true
  }
}
```

### 4. Docker設定
```yaml
# deployment/docker-compose.yml
version: '3.8'

services:
  langgraph-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - \"8000:8000\"
    environment:
      - LANGGRAPH_ENV=production
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
    volumes:
      - ./outputs:/app/outputs
      - ./logs:/app/logs
    networks:
      - langgraph-network

  webhook-server:
    build:
      context: .
      dockerfile: Dockerfile.webhooks
    ports:
      - \"8001:8001\"
    environment:
      - LANGGRAPH_SERVER_URL=http://langgraph-server:8000
    depends_on:
      - langgraph-server
    networks:
      - langgraph-network

networks:
  langgraph-network:
    driver: bridge

volumes:
  outputs:
  logs:
```

```dockerfile
# Dockerfile
FROM python:3.13-slim

WORKDIR /app

# 依存関係のコピーとインストール
COPY pyproject.toml uv.lock ./
RUN pip install uv && uv sync --frozen

# ソースコードのコピー
COPY src/ ./src/
COPY langgraph.json ./

# 出力ディレクトリの作成
RUN mkdir -p outputs logs

EXPOSE 8000

CMD [\"uv\", \"run\", \"langgraph\", \"up\", \"--port\", \"8000\", \"--host\", \"0.0.0.0\"]
```

### 5. 環境設定ファイル
```bash
# .env.development
LANGGRAPH_ENV=development
LANGGRAPH_SERVER_URL=http://localhost:8000
LANGGRAPH_LOG_LEVEL=DEBUG
LANGGRAPH_ENABLE_DEBUGGING=true

# API Keys (開発用)
GOOGLE_API_KEY=your_google_api_key_here
OPENAI_API_KEY=your_openai_api_key_here
LANGSMITH_API_KEY=your_langsmith_api_key_here
TAVILY_API_KEY=your_tavily_api_key_here

# 機能フラグ
ENABLE_AUTO_SAVE=true
ENABLE_PERSISTENCE=true
ENABLE_MONITORING=true
```

```bash
# .env.production
LANGGRAPH_ENV=production
LANGGRAPH_SERVER_URL=https://your-domain.com
LANGGRAPH_LOG_LEVEL=INFO
LANGGRAPH_ENABLE_DEBUGGING=false

# API Keys (本番用 - 実際の値は環境変数で設定)
GOOGLE_API_KEY=${GOOGLE_API_KEY}
OPENAI_API_KEY=${OPENAI_API_KEY}
LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
TAVILY_API_KEY=${TAVILY_API_KEY}

# セキュリティ設定
LANGGRAPH_API_KEY=${LANGGRAPH_API_KEY}
CORS_ORIGINS=https://your-frontend-domain.com

# パフォーマンス設定
MAX_CONCURRENT_REQUESTS=100
REQUEST_TIMEOUT=300
```

### 6. 設定管理クラス
```python
# src/config/langgraph_config.py (新規作成)
from pydantic_settings import BaseSettings
from typing import Optional, List
import os

class LangGraphConfig(BaseSettings):
    \"\"\"LangGraph統合設定\"\"\"
    
    # 基本設定
    env: str = \"development\"
    server_url: str = \"http://localhost:8000\"
    log_level: str = \"INFO\"
    enable_debugging: bool = False
    
    # API Keys
    google_api_key: Optional[str] = None
    openai_api_key: Optional[str] = None
    langsmith_api_key: Optional[str] = None
    tavily_api_key: Optional[str] = None
    
    # LangGraph Server設定
    server_port: int = 8000
    server_host: str = \"0.0.0.0\"
    cors_origins: List[str] = [\"*\"]
    
    # 機能フラグ
    enable_auto_save: bool = True
    enable_persistence: bool = True
    enable_monitoring: bool = True
    
    # パフォーマンス設定
    max_concurrent_requests: int = 100
    request_timeout: int = 300
    
    class Config:
        env_prefix = \"LANGGRAPH_\"
        env_file = \".env\"

def get_config() -> LangGraphConfig:
    \"\"\"設定インスタンスを取得\"\"\"
    return LangGraphConfig()

def load_config_from_file(config_path: str) -> dict:
    \"\"\"設定ファイルから設定を読み込み\"\"\"
    import json
    import yaml
    
    if config_path.endswith('.json'):
        with open(config_path, 'r') as f:
            return json.load(f)
    elif config_path.endswith(('.yml', '.yaml')):
        with open(config_path, 'r') as f:
            return yaml.safe_load(f)
    else:
        raise ValueError(f\"Unsupported config file format: {config_path}\")
```

## 受け入れ基準
- [ ] `langgraph.json`が正しく設定されている
- [ ] `.langgraph/config.yaml`が作成されている
- [ ] `studio-config.json`が設定されている
- [ ] Docker設定ファイルが作成されている
- [ ] 開発・本番用の環境設定ファイルがある
- [ ] 設定管理クラスが実装されている
- [ ] 環境変数による設定上書きが可能
- [ ] 設定バリデーションが実装されている

## 技術的詳細
- **新規ファイル**:
  - `langgraph.json`
  - `.langgraph/config.yaml`
  - `.langgraph/requirements.txt`
  - `studio-config.json`
  - `deployment/docker-compose.yml`
  - `Dockerfile`
  - `.env.development`
  - `.env.production`
  - `src/config/langgraph_config.py`

## 関連Issue
- 依存: エントリーポイント実装 (#30)
- 関連: 全LangGraph統合Issue (#26, #27, #28, #29)

## 優先度
Medium - 統合作業の基盤設定

## 推定工数
2-3日

## 実装手順
1. LangGraph Server設定ファイルの作成
2. CLI設定ファイルの作成
3. Studio設定ファイルの作成
4. Docker設定の作成
5. 環境設定ファイルの作成
6. 設定管理クラスの実装
7. 設定バリデーションの実装
8. ドキュメント作成

## セキュリティ考慮事項
- API キーの適切な管理
- CORS設定の制限
- 本番環境での認証設定
- ログ出力での機密情報除外
